In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

pd.set_option("display.max_columns", None)

df = pd.read_csv("/content/rta_enterprise_dataset.csv")
df.head()

,Date,DayOfWeek,Interval,Queue,Team,Forecast_Calls,Actual_Calls,Scheduled_Agents,Available_Agents,AHT,ACW,Occupancy,Adherence,SLA,ASA,Abandon_Rate,CSAT
0,2026-01-01,Thursday,00:00,General Support,Alpha,6,7,4,3,356,55,66.7,93.1,86,14,1.3,4.59
1,2026-01-01,Thursday,00:00,Technical Support,Delta,6,7,4,4,374,50,50.0,93.7,94,2,0.0,4.86
2,2026-01-01,Thursday,00:00,Billing,Bravo,10,8,4,4,322,39,57.1,93.1,94,2,0.0,4.86
3,2026-01-01,Thursday,00:00,Sales,Alpha,9,10,4,4,359,41,71.4,90.9,82,20,3.3,4.46
4,2026-01-01,Thursday,00:00,VIP,Charlie,4,7,4,3,351,33,66.7,95.2,93,4,0.0,4.81

In [4]:
## Problem Statement

##Business Objective:

##Increase the average Service Level from 73% to at least 80% while maintaining customer satisfaction and operational efficiency.

## Potential Root Causes

##Based on the exploratory analysis, several operational factors may contribute to the low Service Level:

##- High Average Speed of Answer (ASA)
##- High Occupancy
##- Increased Call Volume
##- Customer Abandonment
##- Forecasting inaccuracies

In [9]:
numeric = df.select_dtypes(include="number")

corr = numeric.corr()
root_causes = pd.DataFrame({

"Factor":[
"Average Speed of Answer",
"Occupancy",
"Abandon Rate",
"Actual Calls",
"Forecast Calls",
"AHT",
"Adherence"
],

"Correlation_with_SLA":[
corr.loc["ASA","SLA"],
corr.loc["Occupancy","SLA"],
corr.loc["Abandon_Rate","SLA"],
corr.loc["Actual_Calls","SLA"],
corr.loc["Forecast_Calls","SLA"],
corr.loc["AHT","SLA"],
corr.loc["Adherence","SLA"]
]

})

root_causes

                    Factor  Correlation_with_SLA
0  Average Speed of Answer             -0.999862
1                Occupancy             -0.889309
2             Abandon Rate             -0.994257
3             Actual Calls             -0.568845
4           Forecast Calls             -0.552204
5                      AHT             -0.008220
6                Adherence              0.032945

In [10]:
root_causes = root_causes.sort_values(
    by="Correlation_with_SLA",
    key=abs,
    ascending=False
)

root_causes

                    Factor  Correlation_with_SLA
0  Average Speed of Answer             -0.999862
2             Abandon Rate             -0.994257
1                Occupancy             -0.889309
3             Actual Calls             -0.568845
4           Forecast Calls             -0.552204
6                Adherence              0.032945
5                      AHT             -0.008220

## Conclusion

The analysis suggests that the primary drivers of low Service Level are:

- High customer waiting time (ASA)
- High agent Occupancy
- High customer Abandon Rate

Improving these operational areas is expected to have the greatest impact on Service Level performance.